### ISSUE TITLE
Thanks a lot! / Suggestion: Order the favorites themes list first by light and then by dark themes

### ISSUE THREAD

**Issue by schittli** [chetan/ThemeStar#1]
Hello,

**thanks a lot for sharing your great work!**
it's a very useful extension.

I have a suggestion:
At the moment, ThemeStar lists the favorites Themes in alphabetical order. Unfortunately, this order mixes light and dark themes:
![image](https://user-images.githubusercontent.com/8282673/230742601-62eb2b57-b473-489e-84f5-500cd183f5cd.png)

Therefore, if one tries switching between different dark themes by using the cursor up/down keys, it hurts the eyes because it constantly switches between light and dark themes.

I guess that it's a problem for you to decide if a Theme is light order dark because a theme probably has no property like e.g. `IsLightTheme: True|False`

If that's true, then I propose that you just test if the theme name contains the word 'light' or 'dark', because most names contain one of them😃 
If both words are missing, I propose to assign the theme to the light themes, because it is better to have light themes mixed with dark ones (if one would like to switch between just light themes, then it's probably daytime, and therefore, it does not hurt to see dark themes). With this logic, the dark themes always have just dark themes 😃 

Thanks a lot, kind regards,
Thomas

**Comment by chetan** [comment]
@schittli thanks for the feedback and appreciate the nice review in the marketplace! I Just published v1.1 with this and a few other improvements to the selection dialog. Try it out and let me know what you think!
